import setuptools

setuptools.setup(
    name='lgm',
    version='1.0.0',
    packages=[
        'lgm',
        'mvdream',
    ],
    install_requires=[
        'torch',
        'numpy',
        'tyro',
        'diffusers',
        'einops',
        'accelerate',
        'imageio',
        'lpips',
        'matplotlib',
        'pygltflib',
        'rembg[gpu,cli]',
        'rich',
        'safetensors',
        'scikit-image',
        'scikit-learn',
        'scipy',
        'tqdm',
        'transformers',
        'trimesh',
        'kiui',
        'xatlas',
        'roma',
        'plyfile',
        'ninja',
        'PyMCubes'
    ]
)